services:
  nginx:
    image: nginx:alpine
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - transcendence

  frontend:
    restart: always
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules/
    environment:
      - VITE_API_URL=http://localhost/api
    networks:
      - transcendence

  backend:
    restart: always
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/backend:/app
      - /app/node_modules/
      - ./apps/backend/prisma:/app/prisma
      - ./apps/backend/prisma/dev.db:/app/prisma/dev.db
    env_file:
      - ./apps/backend/.env
    environment:
      - NODE_ENV=development
    networks:
      - transcendence

networks:
  transcendence:
    driver: bridge
