# TODO: test
version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx
    depends_on:
      - frontend
      - auth

  frontend:
    image: nginx:latest
    ports:
      - "5000:5000"
    networks:
      - nginx
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
  elk:
    image: elasticsearch:latest
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana:latest
    ports:
      - "5601:5601"
    depends_on:
      - elk
  logstash:
    image: logstash:latest
    ports:
      - "5601:5601"
    depends_on:
      - elk
  auth:
    image: python:latest
    command: python
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app

networks:
  nginx:
    driver: bridge
  db:
    driver: bridge
