services:
  frontend:
    build:
      context: ./apps/frontend
    networks:
      - transcendence
    depends_on:
      - backend
    ports:
      - "8080:80"
      - "8443:443"

  backend:
    build:
      context: ./apps/backend
    env_file:
      - ./apps/backend/.env
    environment:
      - NODE_ENV=production
    volumes:
      - ./apps/backend/prisma:/app/prisma
    networks:
      - transcendence

networks:
  transcendence:
    driver: bridge
